<a href="https://colab.research.google.com/github/OlenaBogoliubova/DATA-LOVE-ACADEMY/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8)_Bogoliubova.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

# Вектор — варіант 1: random.uniform
import random
vector_uniform = np.array([random.uniform(0, 1) for _ in range(10)])

print("Вектор (random.uniform):")
print(vector_uniform)
print("Розмір:", vector_uniform.shape)

Вектор (random.uniform):
[0.15852526 0.67338149 0.92384484 0.80285785 0.35062738 0.55316771
 0.92899621 0.33990561 0.70911736 0.57597378]
Розмір: (10,)


In [2]:
# Вектор — варіант 2: np.random.rand
vector = np.random.rand(10)

print("\nВектор (np.random.rand):")
print(vector)
print("Розмір:", vector.shape)



Вектор (np.random.rand):
[0.70809664 0.10343202 0.06991095 0.41692458 0.5679082  0.35531553
 0.1504154  0.93974896 0.33052457 0.56757439]
Розмір: (10,)


In [6]:
# Матриця 3x3
matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
])

print("\nМатриця:")
print(matrix)
print("Розмір:", matrix.shape)


Матриця:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
Розмір: (3, 3)


In [9]:
matrix = np.arange(11, 36, 3).reshape(3, 3)

matrix

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [10]:
# 1.
new_vector = np.round(vector + 10, 2)
print(new_vector)

[10.71 10.1  10.07 10.42 10.57 10.36 10.15 10.94 10.33 10.57]


In [11]:
# 2.
new_matrix = matrix * 2
print(new_matrix)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [12]:
# 3.
new_sq_vector = np.square(vector)
print(new_sq_vector)

[0.50140086 0.01069818 0.00488754 0.17382611 0.32251973 0.12624913
 0.02262479 0.8831281  0.10924649 0.32214069]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [16]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [20]:
# 1.
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

result_matrix = B @ A
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [21]:
# 2.
result_matrix @ C

array([[0.5202],
       [0.2846]])

In [22]:
# 3.
result_matrix @ D

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [23]:
# 1.
result_transposed = result_matrix.T

print(result_transposed)

[[0.7281 0.2034]
 [0.5202 0.2846]]


In [25]:
# 2.
vector_transposed = vector.T

print(vector_transposed)
print(vector_transposed.shape)

[0.70809664 0.10343202 0.06991095 0.41692458 0.5679082  0.35531553
 0.1504154  0.93974896 0.33052457 0.56757439]
(10,)


In [27]:
# 3.
column_vector = np.expand_dims(vector, axis=1)
print(vector)
print(vector.shape)

print(column_vector)
print(column_vector.shape)

[0.70809664 0.10343202 0.06991095 0.41692458 0.5679082  0.35531553
 0.1504154  0.93974896 0.33052457 0.56757439]
(10,)
[[0.70809664]
 [0.10343202]
 [0.06991095]
 [0.41692458]
 [0.5679082 ]
 [0.35531553]
 [0.1504154 ]
 [0.93974896]
 [0.33052457]
 [0.56757439]]
(10, 1)


In [28]:
# 4.
column_vector_transposed = column_vector.T

print(column_vector_transposed)
print(column_vector_transposed.shape)

[[0.70809664 0.10343202 0.06991095 0.41692458 0.5679082  0.35531553
  0.1504154  0.93974896 0.33052457 0.56757439]]
(1, 10)
